plugins:
  - uses:
      - plugin: "https://ubiquity-os-plugin-demo-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-command-start-stop-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-command-wallet-main.ubiquity.workers.dev"
  - uses:
      - plugin: "ubiquity-os-marketplace/command-ask@main"
        with:
          model: "anthropic/claude-3.5-sonnet"
          openAiBaseUrl: "https://openrouter.ai/api/v1"
  - uses:
      - plugin: "https://ubiquity-os-command-query-user-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-daemon-pricing-main.ubiquity.workers.dev"
        skipBotEvents: false
  - uses:
      - plugin: "ubiquity-os-marketplace/text-conversation-rewards@main"
        skipBotEvents: false
        with:
          incentives:
            collaboratorOnlyPaymentInvocation: false
            contentEvaluator: {}
            userExtractor: {}
            dataPurge: {}
            formattingEvaluator: {}
            permitGeneration: {}
            githubComment: {}
          evmPrivateEncrypted: "QD2bCW6_Q8KYvI7wmJTfctR7ue4_849XcsZSt0oLEAMRI4oGAWQ4cry3Cvehc3M61vAYMGYdXwA9rY1PnQ2f-8YrYXe6OKjPchJDiRpPvkFvrT073ntVuxpyW4yb0i55DrmKHZiaYfjFjNbIOOsZAqNWidw7HjRVWBxDKooIBKsPv4qL"
          evmNetworkId: 100
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-disqualifier@main"
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-merging@main"
  - uses:
      - plugin: "https://ubiquity-os-comment-vector-embeddings-main.ubiquity.workers.dev"
